# Generated by Django 5.1.2 on 2024-10-21 13:40

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_projectquoterequest_project_due_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='projectquoterequest',
            name='uploaded_files',
        ),
        migrations.AddField(
            model_name='image',
            name='uploaded_files',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
