# Generated by Django 5.1.2 on 2024-10-31 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_filetransfer_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('catalog_items', 'Catalog Items')],
            },
        ),
        migrations.CreateModel(
            name='MessageCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('message_center', 'Message Center')],
            },
        ),
        migrations.CreateModel(
            name='OnlineProofing',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('online_proofing', 'Online Proofing')],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('order', 'Order Administration')],
            },
        ),
        migrations.CreateModel(
            name='PrintReadyFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('print_ready_files', 'Print-Ready Files')],
            },
        ),
        migrations.CreateModel(
            name='WebsiteUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('website_users', 'Website Users')],
            },
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'permissions': [('customers', 'Customer Service')]},
        ),
    ]
