# Generated by Django 5.1.2 on 2024-11-04 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_catalogitem_messagecenter_onlineproofing_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='name',
        ),
        migrations.AlterField(
            model_name='filetransfer',
            name='other_application_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
