# Generated by Django 5.1.2 on 2024-10-21 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_uploaded_files_image_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image_url',
            new_name='path',
        ),
    ]
