# Generated by Django 5.1.2 on 2024-10-22 13:58

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_rename_image_url_image_path'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email_address', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('fax_number', models.CharField(blank=True, max_length=20, null=True)),
                ('company', models.CharField(blank=True, max_length=255)),
                ('city_state_zip', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('preferred_mode_of_response', models.CharField(blank=True, choices=[('Email', 'Email'), ('Phone', 'Phone'), ('Fax', 'Fax')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artwork_provided', models.CharField(blank=True, choices=[('None', 'None'), ('Online file transfer', 'Online file transfer'), ('On disk', 'On disk'), ('Hard copy', 'Hard copy'), ('Film provided', 'Film provided'), ('Please estimate for design', 'Please estimate for design')], max_length=50)),
                ('project_name', models.CharField(max_length=255)),
                ('project_due_date', models.DateField(default=datetime.date.today)),
                ('additional_details', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email_address', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('fax_number', models.CharField(blank=True, max_length=20, null=True)),
                ('company', models.CharField(blank=True, max_length=255)),
                ('city_state_zip', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('preferred_mode_of_response', models.CharField(blank=True, choices=[('Email', 'Email'), ('Phone', 'Phone'), ('Fax', 'Fax')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('you_are_a', models.CharField(choices=[('New Customer', 'New Customer'), ('Current Customer', 'Current Customer')], max_length=50)),
                ('this_is_an', models.CharField(choices=[('Order Request', 'Order Request'), ('Estimate Request', 'Estimate Request')], max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('zip', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=255)),
                ('fax_number', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('pay_tax', models.BooleanField()),
                ('third_party_identifier', models.CharField(max_length=255)),
                ('credit_balance', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='image',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='store.quoterequest'),
        ),
        migrations.DeleteModel(
            name='ProjectQuoteRequest',
        ),
    ]
