# Generated by Django 5.1.2 on 2024-10-22 15:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_quoterequest_request_customer_alter_image_project_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='additional_details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='request',
            name='artwork_provided',
            field=models.CharField(blank=True, choices=[('None', 'None'), ('Online file transfer', 'Online file transfer'), ('On disk', 'On disk'), ('Hard copy', 'Hard copy'), ('Film provided', 'Film provided'), ('Please estimate for design', 'Please estimate for design')], max_length=50),
        ),
        migrations.AddField(
            model_name='request',
            name='project_due_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='request',
            name='project_name',
            field=models.CharField(default='a', max_length=255),
            preserve_default=False,
        ),
    ]
