# Generated by Django 5.1.2 on 2024-11-05 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_group_customer_groups_groupitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupitem',
            name='group',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='groupitem',
            name='customer',
        ),
        migrations.CreateModel(
            name='CustomerGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('customers', models.ManyToManyField(related_name='groups', to='store.customer')),
            ],
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='GroupItem',
        ),
    ]
