# Generated by Django 5.1.2 on 2024-11-05 07:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_remove_groupitem_group_remove_customer_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customergroup',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
