# Generated by Django 5.1.2 on 2024-10-23 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_remove_image_project_image_content_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinquiry',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contactinquiry',
            name='city_state_zip',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contactinquiry',
            name='company',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contactinquiry',
            name='country',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contactinquiry',
            name='preferred_mode_of_response',
            field=models.CharField(blank=True, choices=[('Email', 'Email'), ('Phone', 'Phone'), ('Fax', 'Fax')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='additional_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='city_state_zip',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='company',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='country',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='preferred_mode_of_response',
            field=models.CharField(blank=True, choices=[('Email', 'Email'), ('Phone', 'Phone'), ('Fax', 'Fax')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='city_state_zip',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='company',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='country',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='preferred_mode_of_response',
            field=models.CharField(blank=True, choices=[('Email', 'Email'), ('Phone', 'Phone'), ('Fax', 'Fax')], max_length=50, null=True),
        ),
    ]
