# Generated by Django 5.1.2 on 2024-10-22 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_customer_credit_balance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('quoterequest_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='store.quoterequest')),
                ('you_are_a', models.CharField(choices=[('New Customer', 'New Customer'), ('Current Customer', 'Current Customer')], max_length=50)),
                ('this_is_an', models.CharField(choices=[('Order Request', 'Order Request'), ('Estimate Request', 'Estimate Request')], max_length=50)),
            ],
            options={
                'abstract': False,
            },
            bases=('store.quoterequest',),
        ),
    ]
