# Generated by Django 5.1.2 on 2024-11-05 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_customergroup_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customergroup',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
