# Generated by Django 5.1.2 on 2024-10-24 20:48

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('store', '0009_alter_contactinquiry_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email_address', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('fax_number', models.CharField(blank=True, max_length=20, null=True)),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('city_state_zip', models.CharField(max_length=255, null=True)),
                ('country', models.CharField(max_length=255, null=True)),
                ('preferred_mode_of_response', models.CharField(blank=True, choices=[('Email', 'Email'), ('Phone', 'Phone'), ('Fax', 'Fax')], max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('additional_details', models.TextField(blank=True)),
                ('file_type', models.CharField(choices=[('PC', 'PC'), ('MACINTOSH', 'MACINTOSH')], max_length=50)),
                ('application_type', models.CharField(choices=[('MULTIPLE', 'MULTIPLE (COMPRESSED)'), ('ACROBAT', 'ACROBAT (PDF)'), ('CORELDRAW', 'CORELDRAW'), ('EXCEL', 'EXCEL'), ('FONTS', 'FONTS'), ('FREEHAND', 'FREEHAND'), ('ILLUSTRATOR', 'ILLUSTRATOR'), ('INDESIGN', 'INDESIGN'), ('PAGEMAKER', 'PAGEMAKER'), ('PHOTOSHOP', 'PHOTOSHOP'), ('POWERPOINT', 'POWERPOINT'), ('PUBLISHER', 'PUBLISHER'), ('WORD', 'WORD'), ('QUARKXPRESS', 'QUARKXPRESS'), ('OTHER', 'OTHER')], max_length=255)),
                ('other_application_type', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='artwork_provided',
            field=models.CharField(blank=True, choices=[('None', 'None'), ('Online file transfer', 'Online file transfer'), ('On disk', 'On disk'), ('Hard copy', 'Hard copy'), ('Film provided', 'Film provided'), ('Please estimate for design', 'Please estimate for design')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='project_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='auto')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
