# Generated by Django 5.1.2 on 2024-11-06 07:59

import store.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_customergroup_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinquiry',
            name='fax_number',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[
                                   store.models.validate_number]),
        ),
        migrations.AlterField(
            model_name='contactinquiry',
            name='phone_number',
            field=models.CharField(max_length=20, validators=[
                                   store.models.validate_number]),
        ),
        migrations.AlterField(
            model_name='filetransfer',
            name='fax_number',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[
                                   store.models.validate_number]),
        ),
        migrations.AlterField(
            model_name='filetransfer',
            name='phone_number',
            field=models.CharField(max_length=20, validators=[
                                   store.models.validate_number]),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='fax_number',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[
                                   store.models.validate_number]),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='phone_number',
            field=models.CharField(max_length=20, validators=[
                                   store.models.validate_number]),
        ),
        migrations.AlterField(
            model_name='request',
            name='fax_number',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[
                                   store.models.validate_number]),
        ),
        migrations.AlterField(
            model_name='request',
            name='phone_number',
            field=models.CharField(max_length=20, validators=[
                                   store.models.validate_number]),
        ),
    ]
