# Generated by Django 5.1.2 on 2024-10-25 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_filetransfer_alter_quoterequest_artwork_provided_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoterequest',
            name='this_is_an',
            field=models.CharField(blank=True, choices=[('Order Request', 'Order Request'), ('Quote Request', 'Quote Request')], max_length=50, null=True),
        ),
    ]
