# Generated by Django 5.1.3 on 2024-11-14 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_alter_contactinquiry_phone_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='city',
            new_name='city_state_zip',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='state',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='zip',
        ),
    ]
