# Generated by Django 5.1.3 on 2024-11-14 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_rename_city_customer_city_state_zip_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='third_party_identifier',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
