# Generated by Django 5.1.3 on 2024-11-19 21:10

import cloudinary.models
import django.db.models.deletion
import store.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_alter_customer_third_party_identifier'),
    ]

    operations = [
        migrations.CreateModel(
            name='HTMLFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='auto')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Portal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'permissions': [('portals', 'Portals')],
            },
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='city_state_zip',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='fax_number',
            field=models.CharField(max_length=255, null=True, validators=[store.models.validate_number]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='pay_tax',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(max_length=255, null=True, validators=[store.models.validate_phone_number]),
        ),
        migrations.CreateModel(
            name='PortalContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('is_public', models.BooleanField(default=False)),
                ('customer_groups', models.ManyToManyField(blank=True, related_name='accessible_content', to='store.customergroup')),
                ('customers', models.ManyToManyField(blank=True, related_name='portal_content', to='store.customer')),
                ('html_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.htmlfile')),
                ('portal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content', to='store.portal')),
            ],
        ),
    ]
