# Generated by Django 5.1.3 on 2024-11-20 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_rename_is_public_portalcontent_everyone'),
    ]

    operations = [
        migrations.AddField(
            model_name='portal',
            name='copy_from_portal_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
