# Generated by Django 5.1.3 on 2024-11-21 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_portal_customer_groups_portal_customers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portal',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='portal',
            name='logo',
            field=models.FileField(null=True, upload_to='logos/'),
        ),
    ]
