# Generated by Django 5.1.3 on 2024-11-21 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_rename_name_portal_title_portal_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='portalcontent',
            name='display_in_site_navigation',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='portalcontent',
            name='include_in_site_map',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='portalcontent',
            name='page_redirect',
            field=models.CharField(choices=[('no_redirect', 'No Redirect'), ('external', 'To a page on another website'), ('internal', 'To another page on your site'), ('file', 'To a downloadable file')], default='no_redirect', max_length=50),
        ),
        migrations.CreateModel(
            name='PortalSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('display_in_site_navigation', models.BooleanField(default=True)),
                ('include_in_site_map', models.BooleanField(default=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='store.portalsection')),
                ('portal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='store.portal')),
            ],
        ),
        migrations.AddField(
            model_name='portalcontent',
            name='location',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content', to='store.portalsection'),
        ),
    ]
