# Generated by Django 5.1.3 on 2024-11-26 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_portalcontent_display_in_site_navigation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter the catalog title.', max_length=255, verbose_name='Title')),
                ('specify_low_inventory_message', models.BooleanField(default=False, help_text='Enable to specify a low inventory message.', verbose_name='Specify Low Inventory Message?')),
                ('recipient_emails', models.TextField(blank=True, help_text='Enter recipient email addresses separated by commas.', null=True, verbose_name='Recipient Email(s)')),
                ('subject', models.CharField(blank=True, help_text='Enter the subject for the low inventory message.', max_length=255, null=True, verbose_name='Subject')),
                ('message_text', models.TextField(blank=True, help_text='Enter the message text for low inventory warnings.', null=True, verbose_name='Message Text')),
                ('description', models.TextField(blank=True, help_text='Provide a description for the catalog.', null=True, verbose_name='Description')),
                ('display_items_on_same_page', models.BooleanField(default=False, help_text='Enable to display items on the same page as the catalog.', verbose_name='Display Items on the Same Page as the Catalog?')),
                ('parent_catalog', models.ForeignKey(blank=True, help_text='Select the parent catalog if applicable.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.catalog', verbose_name='Parent Catalog')),
            ],
        ),
    ]
