# Generated by Django 5.1.3 on 2024-11-28 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_catalog'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='file_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
