# Generated by Django 5.1.3 on 2024-12-02 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_file_file_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('is_required', models.BooleanField(default=False)),
                ('attribute_type', models.CharField(choices=[('text_field', 'Text field'), ('text_area', 'Text area'), ('checkboxes', 'Checkboxes'), ('radio_buttons', 'Radio buttons'), ('select_menu', 'Select menu'), ('file_upload', 'File upload')], default='text_field', max_length=20)),
                ('max_length', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='catalogitem',
            options={},
        ),
        migrations.AddField(
            model_name='catalogitem',
            name='available_inventory',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='catalogitem',
            name='can_item_be_ordered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='catalogitem',
            name='default_quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='catalogitem',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='catalogitem',
            name='details_page_per_layout',
            field=models.CharField(default='default', max_length=255),
        ),
        migrations.AddField(
            model_name='catalogitem',
            name='exempt_from_shipping_charges',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='catalogitem',
            name='is_this_item_taxable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='catalogitem',
            name='item_sku',
            field=models.CharField(default='', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='catalogitem',
            name='minimum_inventory',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='catalogitem',
            name='parent_catalog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalog_items', to='store.catalog'),
        ),
        migrations.AddField(
            model_name='catalogitem',
            name='preview_image',
            field=models.ImageField(blank=True, null=True, upload_to='previews/'),
        ),
        migrations.AddField(
            model_name='catalogitem',
            name='pricing_grid',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='catalogitem',
            name='restrict_orders_to_inventory',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='catalogitem',
            name='short_description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='catalogitem',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/'),
        ),
        migrations.AddField(
            model_name='catalogitem',
            name='title',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='catalogitem',
            name='track_inventory_automatically',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='catalogitem',
            name='weight_per_piece_lb',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='catalogitem',
            name='weight_per_piece_oz',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.CreateModel(
            name='AttributeOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=255)),
                ('alternate_display_text', models.CharField(blank=True, max_length=255)),
                ('price_modifier_type', models.CharField(choices=[('dollar', 'Dollar'), ('percentage', 'Percentage')], default='dollar', max_length=10)),
                ('price_modifier_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='store.attribute')),
            ],
        ),
        migrations.CreateModel(
            name='ItemAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True, null=True)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_attributes', to='store.attribute')),
                ('catalog_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='store.catalogitem')),
            ],
        ),
    ]
