# Generated by Django 5.1.3 on 2024-12-03 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0032_alter_catalogitem_pricing_grid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attributeoption',
            old_name='attribute',
            new_name='item_attribute',
        ),
        migrations.RemoveField(
            model_name='attributeoption',
            name='price_modifier_value',
        ),
        migrations.AddField(
            model_name='attribute',
            name='price_modifier_scope',
            field=models.CharField(choices=[('per_unit', 'Per Unit'), ('all_units', 'All units as a whole')], default='per_unit', max_length=20),
        ),
        migrations.AddField(
            model_name='attribute',
            name='price_modifier_type',
            field=models.CharField(choices=[('dollar', 'Dollar'), ('percentage', 'Percentage')], default='dollar', max_length=10),
        ),
        migrations.AddField(
            model_name='attribute',
            name='pricing_tiers',
            field=models.JSONField(blank=True, default=list, help_text="List of dictionaries with 'quantity' and 'price_modifier' keys."),
        ),
        migrations.AddField(
            model_name='attributeoption',
            name='pricing_tiers',
            field=models.JSONField(blank=True, default=list, help_text="List of dictionaries with 'quantity' and 'price_modifier' keys."),
        ),
        migrations.AlterField(
            model_name='attributeoption',
            name='alternate_display_text',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='ItemAttribute',
        ),
    ]
