# Generated by Django 5.1.3 on 2024-12-03 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0033_rename_attribute_attributeoption_item_attribute_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='catalog_item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.catalogitem'),
            preserve_default=False,
        ),
    ]
