# Generated by Django 5.1.3 on 2024-12-03 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0034_attribute_catalog_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='catalog_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='store.catalogitem'),
        ),
    ]
