# Generated by Django 5.1.3 on 2024-12-03 10:06

import store.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0035_alter_attribute_catalog_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogitem',
            name='preview_file',
            field=models.ImageField(blank=True, null=True, upload_to='preview_files/'),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='pricing_tiers',
            field=models.JSONField(blank=True, default=list, help_text="List of dictionaries with 'quantity' and 'price_modifier' keys.", validators=[store.models.validate_pricing_grid]),
        ),
        migrations.AlterField(
            model_name='attributeoption',
            name='pricing_tiers',
            field=models.JSONField(blank=True, default=list, help_text="List of dictionaries with 'quantity' and 'price_modifier' keys.", validators=[store.models.validate_pricing_grid]),
        ),
        migrations.AlterField(
            model_name='catalogitem',
            name='pricing_grid',
            field=models.JSONField(default=list, validators=[store.models.validate_pricing_grid]),
        ),
    ]
