# Generated by Django 5.1.3 on 2024-12-03 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0037_catalogitem_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catalogitem',
            old_name='parent_catalog',
            new_name='catalog',
        ),
    ]
