# Generated by Django 5.1.3 on 2024-12-04 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0040_cart_cartitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='total_price',
            new_name='sub_total',
        ),
    ]
