# Generated by Django 5.1.3 on 2024-12-05 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0041_remove_cartitem_customer_cart_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='product',
            new_name='catalog_item',
        ),
    ]
