# Generated by Django 5.1.3 on 2024-12-06 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0042_rename_product_orderitem_catalog_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlinePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Your Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('payment_method', models.CharField(choices=[('credit_card', 'Use My Credit Card On File'), ('debit_card', 'Use My Debit Account On File')], max_length=50, verbose_name='Payment Method')),
                ('invoice_number', models.CharField(max_length=100, verbose_name='Invoice #')),
                ('po_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='P.O. #')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount')),
                ('additional_instructions', models.TextField(blank=True, null=True, verbose_name='Additional Instructions')),
            ],
            options={
                'verbose_name': 'Online Payment',
                'verbose_name_plural': 'Online Payments',
            },
        ),
    ]
