# Generated by Django 5.1.3 on 2024-12-06 13:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0043_onlinepayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date_needed',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
