# Generated by Django 5.1.3 on 2024-12-10 07:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0046_portalcontentcatalog_portalcontent_catalogs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlinepayment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='portalcontentcatalog',
            unique_together={('portal_content', 'catalog')},
        ),
    ]
