# Generated by Django 5.1.3 on 2024-12-10 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0049_fileexchange'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fileexchange',
            old_name='sender_email',
            new_name='email_address',
        ),
        migrations.RenameField(
            model_name='fileexchange',
            old_name='sender_name',
            new_name='name',
        ),
    ]
