# Generated by Django 5.1.3 on 2024-12-10 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0051_fileexchange_file_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email_address', models.EmailField(max_length=254)),
                ('date', models.DateTimeField()),
                ('tracking_number', models.CharField(blank=True, max_length=255, null=True)),
                ('proof_status', models.CharField(max_length=255)),
                ('recipient_name', models.CharField(max_length=255)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('project_title', models.CharField(blank=True, max_length=255, null=True)),
                ('project_details', models.TextField(blank=True, null=True)),
                ('proof_due_date', models.DateField(blank=True, null=True)),
                ('additional_info', models.TextField(blank=True, null=True)),
            ],
            options={
                'permissions': [('online_proofing', 'Online Proofing')],
            },
        ),
        migrations.DeleteModel(
            name='OnlineProofing',
        ),
    ]
