# Generated by Django 5.1.3 on 2024-12-10 13:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0052_onlineproof_delete_onlineproofing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onlineproof',
            name='date',
        ),
        migrations.AddField(
            model_name='onlineproof',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
