# Generated by Django 5.1.3 on 2024-12-12 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0053_remove_onlineproof_date_onlineproof_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinquiry',
            name='portal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.portal'),
        ),
        migrations.AddField(
            model_name='filetransfer',
            name='portal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.portal'),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='portal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.portal'),
        ),
        migrations.AddField(
            model_name='request',
            name='portal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.portal'),
        ),
    ]
