# Generated by Django 5.1.3 on 2024-12-17 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0054_contactinquiry_portal_filetransfer_portal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default='')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='portalcontent',
            name='html_file',
        ),
        migrations.AddField(
            model_name='portalcontent',
            name='page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.page'),
        ),
        migrations.DeleteModel(
            name='HTMLFile',
        ),
    ]
