# Generated by Django 5.1.3 on 2024-12-17 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0055_page_remove_portalcontent_html_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portalcontent',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='portalcontent',
            name='title',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
