# Generated by Django 5.1.3 on 2024-12-18 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0056_portalcontent_content_portalcontent_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filetransfer',
            name='application_type',
            field=models.CharField(choices=[('PC', 'PC'), ('Macintosh', 'MACINTOSH')], max_length=255),
        ),
        migrations.AlterField(
            model_name='filetransfer',
            name='file_type',
            field=models.CharField(choices=[('Multiple (compressed)', 'MULTIPLE (COMPRESSED)'), ('Acrobat (pdf)', 'ACROBAT (PDF)'), ('CorelDraw', 'CORELDRAW'), ('Excel', 'EXCEL'), ('Fonts', 'FONTS'), ('Freehand', 'FREEHAND'), ('Illustrator', 'ILLUSTRATOR'), ('InDesign', 'INDESIGN'), ('Pagemaker', 'PAGEMAKER'), ('Photoshop', 'PHOTOSHOP'), ('PowerPoint', 'POWERPOINT'), ('Publisher', 'PUBLISHER'), ('Word', 'WORD'), ('QuartXPress', 'QUARKXPRESS'), ('Other', 'OTHER')], max_length=50),
        ),
    ]
