# Generated by Django 5.1.3 on 2024-12-19 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0057_alter_filetransfer_application_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filetransfer',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Pending', 'Pending'), ('Processing', 'Processing'), ('Completed', 'Completed')], default='New', max_length=50),
        ),
        migrations.AddField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Pending', 'Pending'), ('Processing', 'Processing'), ('Completed', 'Completed')], default='New', max_length=50),
        ),
    ]
