# Generated by Django 5.1.4 on 2024-12-21 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0061_staffnotification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StaffNotification',
        ),
    ]
