# Generated by Django 5.1.4 on 2024-12-25 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0064_alter_catalogitem_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customergroup',
            name='customers',
            field=models.ManyToManyField(blank=True, related_name='groups', to='store.customer'),
        ),
    ]
