# Generated by Django 5.1.4 on 2024-12-29 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0068_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogitem',
            name='item_sku',
            field=models.CharField(max_length=100),
        ),
    ]
