# Generated by Django 5.1.4 on 2024-12-30 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0069_alter_catalogitem_item_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filetransfer',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Pending', 'Pending'), ('Processing', 'Processing'), ('Completed', 'Completed'), ('Shipped', 'Shipped')], default='New', max_length=50),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Pending', 'Pending'), ('Processing', 'Processing'), ('Shipped', 'Shipped'), ('Completed', 'Completed')], default='New', max_length=50),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Pending', 'Pending'), ('Processing', 'Processing'), ('Completed', 'Completed'), ('Shipped', 'Shipped')], default='New', max_length=50),
        ),
    ]
