# Generated by Django 5.1.4 on 2025-01-10 14:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0072_portal_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
