# Generated by Django 5.1.4 on 2025-01-11 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0073_catalog_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='portalcontent',
            name='url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
