# Generated by Django 5.1.4 on 2025-01-14 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0074_portalcontent_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portalcontent',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
