# Generated by Django 5.1.4 on 2025-01-14 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0075_alter_portalcontent_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='portalcontent',
            name='can_have_catalogs',
            field=models.BooleanField(default=False),
        ),
    ]
