# Generated by Django 5.1.5 on 2025-01-15 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0078_portalcontent_catalogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogitem',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
