# Generated by Django 5.1.4 on 2025-01-20 20:46

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0086_alter_orderitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogitem',
            name='can_be_edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='portalcontent',
            name='logo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='CartDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('email_address', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('office_number', models.CharField(blank=True, max_length=20, null=True)),
                ('cart_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='store.cartitem')),
            ],
        ),
    ]
