# Generated by Django 5.1.4 on 2025-01-24 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0089_order_address_order_city_state_zip_order_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='sub_total',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
