# Generated by Django 5.1.4 on 2025-01-27 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0091_order_additional_details_order_billing_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Denied', 'Denied'), ('Ordered', 'Ordered')], default='Pending', max_length=50),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6),
            preserve_default=False,
        ),
    ]
