# Generated by Django 5.1.4 on 2025-01-27 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0092_orderitem_status_orderitem_tax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='tax',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
