# Generated by Django 5.1.4 on 2025-01-27 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0093_alter_orderitem_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogitem',
            name='item_type',
            field=models.CharField(choices=[('None Editable', 'None Editable'), ('Business Card', 'Business Card'), ('Others', 'Others')], default='None Editable', max_length=50),
        ),
    ]
