# Generated by Django 5.1.4 on 2025-01-27 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0094_catalogitem_item_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogitem',
            name='item_type',
            field=models.CharField(choices=[('Non-editable', 'Non-editable'), ('Business Card', 'Business Card'), ('Others', 'Others')], default='Non-editable', max_length=50),
        ),
    ]
