# Generated by Django 5.1.5 on 2025-02-05 11:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0097_alter_cart_customer_alter_order_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinquiry',
            name='tracking_number',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name='filetransfer',
            name='tracking_number',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_number',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='tracking_number',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name='request',
            name='tracking_number',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
