# Generated by Django 5.1.5 on 2025-02-06 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0098_contactinquiry_tracking_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
