# Generated by Django 5.1.6 on 2025-02-19 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0102_alter_shipment_shipment_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='portal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.portal'),
        ),
    ]
