# Generated by Django 5.1.6 on 2025-02-20 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0105_alter_cart_portal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.customer'),
        ),
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together={('customer', 'portal')},
        ),
    ]
