# Generated by Django 5.1.6 on 2025-02-21 20:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0107_cartdetails_extension'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartdetails',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cartdetails',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
