# Generated by Django 5.1.6 on 2025-02-24 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0108_cartdetails_created_at_cartdetails_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlinepayment',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Invoice #'),
        ),
        migrations.AlterField(
            model_name='onlinepayment',
            name='po_number',
            field=models.CharField(default=1, max_length=100, verbose_name='P.O. #'),
            preserve_default=False,
        ),
    ]
