# Generated by Django 5.1.6 on 2025-02-25 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0111_itemdetails'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartDetails',
        ),
    ]
