# Generated by Django 5.1.6 on 2025-02-25 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0112_delete_cartdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemdetails',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='itemdetails',
            name='object_id',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_items', to='store.itemdetails'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='store.itemdetails'),
        ),
    ]
