# Generated by Django 5.1.6 on 2025-02-26 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0113_remove_itemdetails_content_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemdetails',
            name='email_address',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='itemdetails',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='itemdetails',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
