# Generated by Django 5.1.6 on 2025-02-27 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0114_alter_itemdetails_email_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='po_number',
            field=models.CharField(default='1234', max_length=100),
            preserve_default=False,
        ),
    ]
