# Generated by Django 5.1.6 on 2025-03-13 12:37

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0115_alter_order_po_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogitem',
            name='empty_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='catalogitem',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='catalogitem',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True),
        ),
        migrations.CreateModel(
            name='TemplateField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('date', 'Date'), ('email', 'Email'), ('phone', 'Phone')], default='text', max_length=20)),
                ('default_value', models.CharField(blank=True, max_length=255, null=True)),
                ('position_x', models.IntegerField(default=0)),
                ('position_y', models.IntegerField(default=0)),
                ('font_size', models.IntegerField(default=12)),
                ('font_color', models.CharField(default='#000000', max_length=20)),
                ('font_family', models.CharField(default='Arial', max_length=50)),
                ('bold', models.BooleanField(default=False)),
                ('italic', models.BooleanField(default=False)),
                ('width', models.IntegerField(default=100)),
                ('height', models.IntegerField(default=30)),
                ('max_length', models.IntegerField(default=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('catalog_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='template_fields', to='store.catalogitem')),
            ],
        ),
    ]
