# Generated by Django 5.1.6 on 2025-03-24 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0118_editablecatalogitemfile_back_svg_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='editablecatalogitemfile',
            name='file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
