# Generated by Django 5.1.6 on 2025-03-24 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0119_editablecatalogitemfile_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatefield',
            name='editable_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='template_fields', to='store.editablecatalogitemfile'),
        ),
    ]
