# Generated by Django 5.1.6 on 2025-03-24 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0120_templatefield_editable_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='templatefield',
            old_name='field_name',
            new_name='label',
        ),
        migrations.RenameField(
            model_name='templatefield',
            old_name='default_value',
            new_name='placeholder',
        ),
    ]
