# Generated by Django 5.1.6 on 2025-03-25 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0121_rename_field_name_templatefield_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='editablecatalogitemfile',
            name='catalog_item_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='editablecatalogitemfile',
            name='file_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
