# Generated by Django 5.1.6 on 2025-03-25 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0122_editablecatalogitemfile_catalog_item_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editablecatalogitemfile',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirming', 'Confirming'), ('Processing', 'Processing')], default='Pending', max_length=20),
        ),
    ]
