# Generated by Django 5.1.6 on 2025-03-26 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0123_alter_editablecatalogitemfile_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editablecatalogitemfile',
            name='catalog_item_name',
            field=models.CharField(default='New name', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='editablecatalogitemfile',
            name='file_name',
            field=models.CharField(default='test.psd', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='editablecatalogitemfile',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirming', 'Confirming'), ('Processing', 'Processing'), ('Updated', 'Updated'), ('Approving', 'Approving')], default='Pending', max_length=20),
        ),
    ]
