# Generated by Django 5.1.6 on 2025-03-27 17:39

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0124_alter_editablecatalogitemfile_catalog_item_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalogitem',
            name='empty_image',
        ),
        migrations.RemoveField(
            model_name='catalogitem',
            name='height',
        ),
        migrations.RemoveField(
            model_name='catalogitem',
            name='width',
        ),
        migrations.RemoveField(
            model_name='editablecatalogitemfile',
            name='catalog',
        ),
        migrations.RemoveField(
            model_name='editablecatalogitemfile',
            name='catalog_item_name',
        ),
        migrations.RemoveField(
            model_name='editablecatalogitemfile',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='editablecatalogitemfile',
            name='description',
        ),
        migrations.AddField(
            model_name='catalogitem',
            name='back_svg_code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='catalogitem',
            name='file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='business_card'),
        ),
        migrations.AddField(
            model_name='catalogitem',
            name='file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='catalogitem',
            name='file_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='catalogitem',
            name='front_svg_code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='catalogitem',
            name='sides',
            field=models.CharField(choices=[('Front Only', 'Front Only'), ('Front and Back', 'Front and Back')], default='Front Only', max_length=20),
        ),
        migrations.AddField(
            model_name='catalogitem',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirming', 'Confirming'), ('Processing', 'Processing'), ('Updated', 'Updated'), ('Approving', 'Approving'), ('Approved', 'Approved')], default='Approved', max_length=20),
        ),
    ]
