# Generated by Django 5.1.8 on 2025-04-06 09:19

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0126_cartitem_image_orderitem_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='back_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='back_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
