# Generated by Django 5.1.8 on 2025-04-07 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0127_cartitem_back_image_orderitem_back_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templatefield',
            name='field_type',
            field=models.CharField(choices=[('text', 'text'), ('image', 'image'), ('date', 'date'), ('email', 'email'), ('tel', 'tel')], default='text', max_length=20),
        ),
    ]
