# Generated by Django 5.1.8 on 2025-04-11 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0130_cartitem_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='back_pdf_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='front_pdf_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
