# Generated by Django 5.1.8 on 2025-04-11 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0132_templatefield_prefix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templatefield',
            name='prefix',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
