# Generated by Django 5.1.8 on 2025-04-23 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0133_alter_templatefield_prefix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templatefield',
            name='field_type',
            field=models.CharField(choices=[('text', 'text'), ('image', 'image'), ('date', 'date'), ('email', 'email'), ('tel', 'tel'), ('number', 'number')], default='text', max_length=20),
        ),
    ]
