# Generated by Django 5.1.2 on 2024-10-30 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_user_managers_rename_first_name_user_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.EmailField(error_messages={'unique': 'A user with that username already exists.'}, max_length=254, null=True, unique=True),
        ),
    ]
