# Generated by Django 5.1.3 on 2024-11-10 22:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_user_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtendedGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.group')),
            ],
        ),
    ]
