# Generated by Django 5.1.4 on 2024-12-23 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_blacklistedtoken'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='blacklistedtoken',
            table=None,
        ),
    ]
