# Generated by Django 5.1.5 on 2025-02-07 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_blacklistedtoken_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendedgroup',
            name='for_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
