# Generated by Django 5.1.2 on 2024-10-21 13:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectquoterequest',
            name='project_due_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
