# Generated by Django 5.1.2 on 2024-10-21 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_manager', '0003_remove_image_image_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='uploaded_files',
            new_name='image_url',
        ),
    ]
