# Generated by Django 5.1.2 on 2024-10-21 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_manager', '0005_rename_image_url_image_path'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProjectQuoteRequest',
            new_name='QuoteRequest',
        ),
    ]
